version: "3"
services:
  marketplace_api:
    build: .
    container_name: marketplace_app
    restart: always
    ports:
      - "8083:8083"
    environment:
      - MYSQL_HOST=marketplace_mysql_server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=marketplace_db
      - IMG_UPLOAD_DIRECTORY=./images
    networks:
      - marketplace_network
    depends_on:
      - marketplace_mysql_server
      - esa
      - pla
      - sma
  marketplace_mysql_server:
    image: mysql:8.0.32
    container_name: marketplace_mysql_server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=marketplace_db
    ports:
      - "3307:3306"
    networks:
      - marketplace_network
  sma:
    image: elleined/sma
    container_name: marketplace_sma
    restart: always
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=marketplace_mysql_server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=sma_db
    networks:
      - marketplace_network
    depends_on:
      - marketplace_mysql_server
  pla:
    image: elleined/pla
    container_name: "marketplace_pla"
    restart: always
    ports:
      - "8082:8082"
    environment:
      - MYSQL_HOST=marketplace_mysql_server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=pla_db
    networks:
      - marketplace_network
    depends_on:
      - marketplace_mysql_server
  esa:
    image: elleined/esa
    container_name: marketplace_esa
    restart: always
    ports:
      - "8091:8091"
    networks:
      - marketplace_network
    environment:
      - MAIL_USERNAME=juandelacruz@gmail.com
      - MAIL_PASSWORD=abcdefghijklmnop
networks:
  marketplace_network:
    name: marketplace_network
    ipam:
      driver: default
    external: false

