version: "3.8"
services:
  ma_app:
    build: .
    image: elleined/ma
    container_name: ma_app
    restart: always
    volumes:
      - image_volume:/images
    ports:
      - "8083:8083"
    environment:
      - MYSQL_HOST=marketplace_mysql_server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=marketplace_db
      - IMG_UPLOAD_DIRECTORY=./images
    networks:
      - marketplace_network
    depends_on:
      marketplace_mysql_server:
        condition: service_healthy
      marketplace_esa:
        condition: service_healthy
      marketplace_pla:
        condition: service_healthy
      marketplace_sma:
        condition: service_healthy
  marketplace_mysql_server:
    image: mysql:8.0.32
    container_name: marketplace_mysql_server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=marketplace_db
    ports:
      - "3307:3306"
    networks:
      - marketplace_network
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 1m
      timeout: 15s
      retries: 2
      start_period: 10s      
  marketplace_sma:
    image: elleined/sma
    container_name: marketplace_sma
    restart: always
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=marketplace_mysql_server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=sma_db
    networks:
      - marketplace_network
    healthcheck:
      test: curl http://localhost:8081/api/v1/sma/actuator/health
      interval: 1m
      timeout: 15s
      retries: 2
      start_period: 10s      
    depends_on:
      marketplace_mysql_server:
        condition: service_healthy
  marketplace_pla:
    image: elleined/pla
    container_name: marketplace_pla
    restart: always
    ports:
      - "8082:8082"
    environment:
      - MYSQL_HOST=marketplace_mysql_server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=pla_db
    networks:
      - marketplace_network
    healthcheck:
      test: curl http://localhost:8082/api/v1/pla/actuator/health
      interval: 1m
      timeout: 15s
      retries: 2
      start_period: 10s      
    depends_on:
      marketplace_mysql_server:
        condition: service_healthy
  marketplace_esa:
    image: elleined/esa
    container_name: marketplace_esa
    restart: always
    ports:
      - "8091:8091"
    networks:
      - marketplace_network
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    healthcheck:
      test: curl http://localhost:8091/api/v1/esa/actuator/health
      interval: 1m
      timeout: 15s
      retries: 2
      start_period: 10s      
networks:
  marketplace_network:
    name: marketplace_network
    ipam:
      driver: default
    external: false
volumes:
  image_volume:
    external: false
    driver: local
    name: image_volume
